### ISSUE TITLE
the event is not working

### ISSUE THREAD

**Issue by wiwengweng** [le5le-com/topology-vue-ts#1]
Hi, the project is able to build and run. But I add event to the rectangle and try to change the iconColor. But I click the rectangle, without success. 
Here is the code:

I had a rectangle tagged 'b', and add the following.

````
var node = topology.find('b');
node.iconColor = '#20afe0';
topology.render();
````

**Comment by SignDawn** [comment]
You had locked the canvas? We test it ，it's ok!
